
HEIGHT = 600
WIDTH = 800

INIT_BALL_SPEED = 0.1

PADDLE_HEIGHT = 1
PADDLE_WIDTH = 5

PADDLE_X_POS = WIDTH//2 - 50
PADDLE_Y_POS = 0

SCORE_ALIGNMENT = "center"
SCORE_FONT = ("Courier", 60, "normal")
